// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTW2yFyVKRfU04TAxd4eFteIfUHl9r-tA',
    appId: '1:473403818949:web:e19a1fffbcb4b749b041ac',
    messagingSenderId: '473403818949',
    projectId: 'homeventory-aa13f',
    authDomain: 'homeventory-aa13f.firebaseapp.com',
    storageBucket: 'homeventory-aa13f.appspot.com',
    measurementId: 'G-ETL718LHH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_uhYgXksnm5vAa17nbHurWTky2k0q0AY',
    appId: '1:473403818949:android:23ee367604e6fce2b041ac',
    messagingSenderId: '473403818949',
    projectId: 'homeventory-aa13f',
    storageBucket: 'homeventory-aa13f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDalOwV-zqnIIvYqZzHh2ek-e_yMC43a0k',
    appId: '1:473403818949:ios:2c7c3b495c5e02d8b041ac',
    messagingSenderId: '473403818949',
    projectId: 'homeventory-aa13f',
    storageBucket: 'homeventory-aa13f.appspot.com',
    iosClientId: '473403818949-gjvo2bd2147cnnoj2b5kh26almqqgc26.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeventory',
  );
}
